# Dockerfile.pytest
FROM base-service:latest

WORKDIR /app

# Копируем тесты и конфиги
COPY requirements.txt .
COPY pytest.ini .
COPY tests/ ./tests/

# Устанавливаем зависимости
RUN pip install --no-cache-dir -r requirements.txt

# По умолчанию запускаем pytest
CMD ["pytest"]